name: IPEO_testing
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
prefix: C:\Users\noest\anaconda3\envs\IPEO_testing
